language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install p7zip-full

install:
  - node --version
  - npm --version
  - npm install

after_success:
  - npm run coveralls

os:
  - linux
